### PR TITLE
Pass through all env vars when building

### LINKED ISSUE #48: Broken in Go 1.12?
I tried building our astilectron app on go1.12.1 and I get this error:

```/home/frew/go/bin/astilectron-bundler -v -l -d -o "/home/frew/go/src/go.zr.org/auth/zam/output"
DEBU[0000] Creating /home/frew/go/src/go.zr.org/auth/zam/output  app_name=
DEBU[0000] Bundling for environment darwin/amd64         app_name=
DEBU[0000] Binding data                                  app_name=
DEBU[0000] Removing /run/shm/astibundler/bind            app_name=
DEBU[0000] Creating /run/shm/astibundler/bind            app_name=
DEBU[0000] Creating /run/shm/astibundler/bind/vendor_astilectron_bundler  app_name=
DEBU[0000] Creating /run/shm/astibundler/cache           app_name=
DEBU[0000] /run/shm/astibundler/cache/astilectron-0.30.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.30.0.zip  app_name=
DEBU[0000] Copying /run/shm/astibundler/cache/astilectron-0.30.0.zip to /run/shm/astibundler/bind/vendor_astilectron_bundler/astilectron.zip  app_name=
DEBU[0000] /run/shm/astibundler/cache/electron-darwin-amd64-4.0.1.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip  app_name=
DEBU[0000] Copying /run/shm/astibundler/cache/electron-darwin-amd64-4.0.1.zip to /run/shm/astibundler/bind/vendor_astilectron_bundler/electron.zip  app_name=
DEBU[0000] Creating /run/shm/astibundler/bind/resources  app_name=
DEBU[0000] Copying /home/frew/go/src/go.zr.org/auth/zam/cmd/zam/resources to /run/shm/astibundler/bind/resources  app_name=
DEBU[0000] Generating /home/frew/go/src/go.zr.org/auth/zam/cmd/zam/bind_darwin_amd64.go  app_name=
DEBU[0001] Removing /home/frew/go/src/go.zr.org/auth/zam/output/darwin-amd64  app_name=
DEBU[0001] Creating /home/frew/go/src/go.zr.org/auth/zam/output/darwin-amd64  app_name=
DEBU[0001] Building for os darwin and arch amd64         app_name=
DEBU[0001] Executing go build -ldflags -X "main.AppName=zam" -X "main.BuiltAt=2019-03-27 08:44:43.753300385 -0700 PDT m=+1.965728088" -o /home/frew/go/src/go.zr.org/auth/zam/output/darwin-amd64/binary .  app_name=
FATA[0002] bundling failed: bundling for environment darwin/amd64 failed: building failed: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
: exit status 1  app_name=
```

I know the solution to this, but I think we should stop whitelisting the env vars we pass through to the build and instead pass *all* env vars through, overriding a specific subset.  What do you think?

### PR DESCRIPTION
**Pull request by frioux**
Should fix builds on Go 1.12 and also reduce build time for older versions of Go thanks to allowing use of the build cache.

Fixes #48

### CODE REVIEW

File: bundler.go [hunk 1]
```diff
@@ -375,17 +375,18 @@ func (b *Bundler) bundle(e ConfigurationEnvironment) (err error) {
...
-		"GOCACHE=" + os.Getenv("GOCACHE"),
-		"GOFLAGS=" + os.Getenv("GOFLAGS"),
-		"GOPATH=" + gp,
-		"GOROOT=" + os.Getenv("GOROOT"),
-		"PATH=" + os.Getenv("PATH"),
-		"TEMP=" + os.Getenv("TEMP"),
-		"TAGS=" + os.Getenv("TAGS"),
-	}
+	cmd.Env = os.Environ()
+	cmd.Env = append(cmd.Env,
```
Comment (asticode) [inline bundler.go]: Is there a reason why you still append `GOCACHE`, `GOFLAGS`, `GOROOT`, `PATH`, `TEMP` and `TAGS`?

From my understanding, `os.Environ()` is already taking care of that, isn't it?

**Comment by frioux** [comment]
That was just an accident; feel free to remove those lines or I will
when I have a chance (probably Tuesday.)

On Sat, Mar 30, 2019 at 12:30:41AM -0700, Quentin Renard wrote:
> asticode requested changes on this pull request.
> 
> 
> 
> > @@ -375,17 +375,18 @@ func (b *Bundler) bundle(e ConfigurationEnvironment) (err error) {
>  	astilog.Debugf("Building for os %s and arch %s", e.OS, e.Arch)
>  	var binaryPath = filepath.Join(environmentPath, "binary")
>  	var cmd = exec.Command(b.pathGoBinary, "build", "-ldflags", b.ldflags.String(), "-o", binaryPath, b.pathBuild)
> -	cmd.Env = []string{
> -		"GOARCH=" + e.Arch,
> -		"GOOS=" + e.OS,
> -		"GOCACHE=" + os.Getenv("GOCACHE"),
> -		"GOFLAGS=" + os.Getenv("GOFLAGS"),
> -		"GOPATH=" + gp,
> -		"GOROOT=" + os.Getenv("GOROOT"),
> -		"PATH=" + os.Getenv("PATH"),
> -		"TEMP=" + os.Getenv("TEMP"),
> -		"TAGS=" + os.Getenv("TAGS"),
> -	}
> +	cmd.Env = os.Environ()
> +	cmd.Env = append(cmd.Env,
> 
> Is there a reason why you still append `GOCACHE`, `GOFLAGS`, `GOROOT`, `PATH`, `TEMP` and `TAGS`?
> 
> From my understanding, `os.Environ()` is already taking care of that, isn't it?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/asticode/go-astilectron-bundler/pull/49#pullrequestreview-220811494

-- 
fREW Schmidt
https://blog.afoolishmanifesto.com

**Comment by asticode** [comment]
I'll merge the PR and remove them myself.
Cheers

**Comment by frioux** [comment]
thanks!
